name: 'build-test'

on:
  push:
    branches:
        - main

env:
  SLACK_USER_ID_MAP: ${{ secrets.SLACK_USER_ID_MAP }}
  SLACK_CONVERSATION_ID: ${{ secrets.SLACK_CONVERSATION_ID }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
      # currently disable slack testing until a new account is available
      # - uses: ./
      #   with:
      #     status: 'success'
      #     scopes: '{ "scope": ["@devicepilot/one", "@devicepilot/two"] }'
      #     version: 'refs/tags/v4.1.3'
  # test: # make sure the action works on a clean machine without building
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./
  #       with:
  #         status: 'success'
  #         scopes: '{ "scope": ["@devicepilot/one", "@devicepilot/two"] }'
  #         version: 'refs/tags/v4.1.3'

